config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'home/index'

  resources :github_jobs, only: [:index, :show]

  resources :hackernews_jobs, only: [:index, :show]

  resources :stackoverflow_jobs, only: [:index, :show]

  resources :all, only: [:index]

  resources :results, only: :index

end

app/models/github_job.rb
class GithubJob < ActiveRecord::Base

  include PgSearch

  multisearchable :against => [:title, :description, :location]

end

app/models/hackernews_job.rb
class HackernewsJob < ActiveRecord::Base

  include PgSearch

  multisearchable :against => [:title]

end

app/models/stackoverflow_job.rb
class StackoverflowJob < ActiveRecord::Base

  include PgSearch

  multisearchable :against => [:title, :description, :categories]

end

app/controllers/all_controller.rb
class AllController < ApplicationController

  def index
    @gh_jobs = GithubJob.first(15)
    @hn_jobs = HackernewsJob.first(15)
    @so_jobs = StackoverflowJob.first(15)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/github_jobs_controller.rb
class GithubJobsController < ApplicationController

  # GET /github_jobs
  # GET /github_jobs.json
  def index
    @github_jobs = GithubJob.all.paginate(page: params[:page], per_page: 25)
  end

  # GET /github_jobs/1
  # GET /github_jobs/1.json
  def show
    @github_job = GithubJob.find(params[:id])
    @company_logo = @github_job.company_logo
  end

end

app/controllers/hackernews_jobs_controller.rb
class HackernewsJobsController < ApplicationController

  def index
    @hn_jobs = HackernewsJob.all.paginate(page: params[:page], per_page: 25)
  end

  def show
    @hn_job = HackernewsJob.find(params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController

  def index
    @results = PgSearch.multisearch(params[:query]).paginate(page: params[:page], per_page: 25)
    @count = @results.length
  end

end

app/controllers/stackoverflow_jobs_controller.rb
class StackoverflowJobsController < ApplicationController

  def index
    @so_jobs = StackoverflowJob.all.paginate(page: params[:page], per_page: 25)
  end

  def show
    @so_job = StackoverflowJob.find(params[:id])
  end

end

app/helpers/all_helper.rb
module AllHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/github_jobs_helper.rb
module GithubJobsHelper
end

app/helpers/hackernews_jobs_helper.rb
module HackernewsJobsHelper

  def hnLink(id)
    id = id.to_s
    url = 'https://news.ycombinator.com/item?id=' + id
    return url
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/stackoverflow_jobs_helper.rb
module StackoverflowJobsHelper
end

app/views/all/index.html.erb
<div class="all-jobs">
    <div class="container">
        <h1 class="text-center">All Jobs</h1>
        <br>
        <div class="col-xs-12 col-sm-4 col-md-4 job-column">
            <h3>Latest from Stack Overflow</h3>
            <div class="clearfix">
            <hr>
            </div>
            <% @so_jobs.each do |job|  %>
                <p><%= link_to job.title, stackoverflow_job_path(job) %></p>
            <% end %>
        </div>

        <div class="col-xs-12 col-sm-4 col-md-4 job-column">
            <h3>Latest from Github</h3>
            <div class="clearfix">
            <hr>
            </div>
            <% @gh_jobs.each do |job|  %>
                <p><%= link_to job.title, github_job_path(job) %></p>
            <% end %>
        </div>

        <div class="col-xs-12 col-sm-4 col-md-4 job-column">
            <h3>Latest from Hacker News</h3>
            <div class="clearfix">
            <hr>
            </div>
            <% @hn_jobs.each do |job|  %>
                <p><%= link_to job.title, hackernews_job_path(job) %></p>
            <% end %>
        </div>
    </div>
</div>

app/views/github_jobs/index.html.erb
<div class="so-jobs">
    <div class="container">
        <h1 class="text-center">Github Jobs</h1>
        <br>

        <% @github_jobs.each do |github_job| %>
            <h4>
                <%= link_to github_job.title, github_job %>
                <small>
                    <%= github_job.location %>
                </small>
            </h4>
            <p>
                <%= github_job.github_type %>
                at
                <%= github_job.company %>
            </p>
            <hr>
        <% end %>

        <%= will_paginate @github_jobs, renderer: BootstrapPagination::Rails %>

    </div>
</div>

app/views/github_jobs/show.html.erb
<div class="gh-job-single">
    <div class="container">

        <h1 class="text-center">
            <%= @github_job.title %>
        </h1>
        <h3 class="text-center">
            <%= @github_job.location %>
            <span> - </span>
            <%= @github_job.company %>
        </h3>

        <hr>

        <div class="row-fluid text-center">
            <% if @company_logo.present? %>
                <%= image_tag @company_logo,
                    alt: @github_job.company,
                        class: 'company-logo'
                %>
            <% end %>
        </div>

        <div class="row-fluid top-info clearfix">
            <div class="col-xs-12 col-sm-6 col-md-6">
                <p>
                    <p><%= @github_job.github_type %></p>
                    <p><strong>How to apply:</strong></p>
                    <%= raw @github_job.how_to_apply %>
                </p>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6">
                <p>
                    <p class="text-right"><%= link_to 'View on Github', @github_job.url %></p>
                    <p class="text-right">
                        <% if !@github_job.company_url.nil? %>
                            <%= link_to 'Company Website', @github_job.company_url %>
                        <% end %>
                    </p>
                    <p class="text-right"><%= @github_job.created_at %></p>
                </p>
            </div>
        </div>

        <div class="col-md-12 body-info clearfix">
            <h2 class="text-center">About this Job</h2>
            <%= raw @github_job.description %>
        </div>

    </div>
</div>

app/views/hackernews_jobs/index.html.erb
<div class="hn-jobs">
    <div class="container">
        <h1 class="text-center">Hacker News Jobs</h1>
        <br>

        <% @hn_jobs.each do |hn_job| %>
            <h4>
                <%= link_to hn_job.title, hackernews_job_path(hn_job) %>
                <i>
                    -  <%= hn_job.by %>
                </i>
            </h4>
            <hr>
        <% end %>

        <%= will_paginate @hn_jobs, renderer: BootstrapPagination::Rails %>

    </div>
</div>

app/views/hackernews_jobs/show.html.erb
<div class="hn-job-single">
    <div class="container">
        <h1 class="text-center">
            <%= @hn_job.title %>
        </h1>
        <hr>

        <div class="row-fluid top-info clearfix">
            <div class="col-md-12">
                <p>
                    Posted by:
                    <span>
                        <%= @hn_job.by %>
                    </span>
                </p>
                <p>
                    <%= link_to 'View on HN', hnLink(@hn_job.hn_id), :target => "_blank" %>
                </p>
                <p>
                    <% if !@hn_job.url.empty? %>
                        <%= link_to 'Company Website', @hn_job.url, :target => "_blank" %>
                    <% end %>
                <p>
                    <%= Time.at(@hn_job.time.to_i) %>
                </p>
            </div>
        </div>

        <div class="col-md-12 body-info clearfix">
            <% if @hn_job.text.empty? %>
                <p class="text-center">No description provided</p>
            <% else %>
                <h2 class="text-center">About this Job</h2>
                <%= raw @hn_job.text %>
            <% end %>
        </div>

    </div>
</div>

app/views/home/index.html.erb
<div class="home">
    <div class="container">
        <div class="home-name">
            <h1>HCKRJOBS</h1>
            <p>An aggregation of the best startup and developer jobs from around the web</p>
        </div>
        <div class="home-search">
            <%= render 'layouts/searchform' %>
        </div>
        <hr>
        <div class="home-categories">
            <div class="col-xs-12 col-sm-6 col-md-4 col-md-offset-2">
                <h4>Technologies</h4>
                <ul>
                    <li>
                        <%= link_to 'Ruby', results_path(:query => 'ruby') %>
                    </li>
                    <li>
                        <%= link_to 'Python', results_path(:query => 'python') %>
                    </li>
                    <li>
                        <%= link_to 'C++', results_path(:query => 'c++') %>
                    </li>
                    <li>
                        <%= link_to 'Functional Programming',
                        results_path(:query => 'functional programming')
                        %>
                    </li>
                    <li>
                        <%= link_to 'Javascript / Node.js',
                        results_path(:query => 'node.js javascript')
                        %>
                    </li>
                    <li>
                        <%= link_to 'iOS', results_path(:query => 'iOS') %>
                    </li>
                </ul>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4">
                <h4>Locations</h4>
                <ul>
                    <li>
                        <%= link_to 'Remote', results_path(:query => 'Remote') %>
                    </li>
                    <li>
                        <%= link_to 'San Francisco', results_path(:query => 'San Francisco') %>
                    </li>
                    <li>
                        <%= link_to 'Toronto', results_path(:query => 'Toronto') %>
                    </li>
                    <li>
                        <%= link_to 'London',
                        results_path(:query => 'London')
                        %>
                    </li>
                    <li>
                        <%= link_to 'New York',
                        results_path(:query => 'New York')
                        %>
                    </li>
                    <li>
                        <%= link_to 'Chicago', results_path(:query => 'Chicago') %>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="container">
        <hr>
        <p>
            <span>HCKRJOBS by Cody Reichert</span>
            <span class="text-right pull-right">Questions or comments: codyreichert@gmail.com</span>
        </p>
    </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav>

    <div class="nav container">

        <div class="col-md-12">
            <div class="pull-left logo">
                <%= link_to 'HCKRJOBS', root_path %>
            </div>
            <div class="pull-right">
                <%= link_to 'Latest', all_index_path %>

                <span> | </span>

                <%= link_to 'Github Jobs', github_jobs_path %>

                <span> | </span>

                <%= link_to 'HN Jobs', hackernews_jobs_path %>

                <span> | </span>

                <%= link_to 'Stack Overflow Jobs', stackoverflow_jobs_path %>
                <span> | </span>

                <%= link_to 'Search', results_path(query: 'Python') %>
            </div>
        </div>
    </div>

</nav>

app/views/layouts/_searchform.html.erb
<%= form_tag results_path, method: :get, class: 'job-search-wide' do %>
    <%= text_field_tag :query, params[:query],
        class: 'job-search-input',
        placeholder: 'ruby on rails'
    %>
    <%= submit_tag "Search", name: nil, class: 'job-search-submit' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>New</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div class="wrap">
        <div class="row-fluid">
            <%= render 'layouts/navigation' %>
            <%= yield %>
        </div>
    </div>

    <%= render 'layouts/footer' %>

</body>
</html>

app/views/results/index.html.erb
<div class="search-jobs">
    <div class="container">
        <h1 class="text-center">Search Jobs</h1>
        <br>

        <div class="results-search">
            <%= render 'layouts/searchform' %>
        </div>

        <h3>Results</h3>
        <p>
            <small>Showing <%= @results.length %> of <%= @results.total_entries %> results</small>
        </p>

        <% @results.each do |result| %>
            <p>
                <%= link_to result.searchable.title, result.searchable %>
            </p>
        <% end %>

        <%= will_paginate @results, renderer: BootstrapPagination::Rails %>

    </div>
</div>

app/views/stackoverflow_jobs/index.html.erb
<div class="so-jobs">
    <div class="container">
        <h1 class="text-center">Stack Overflow Jobs</h1>
        <br>

        <% @so_jobs.each do |job| %>
            <h4>
                <%= link_to job.title, stackoverflow_job_path(job) %>
            </h4>
            <h4>
                <small>
                    <%= job.categories %>
                </small>
            </h4>
            <hr>
        <% end %>

        <%= will_paginate @so_jobs, renderer: BootstrapPagination::Rails %>

    </div>
</div>

app/views/stackoverflow_jobs/show.html.erb
<div class="so-job-single">
    <div class="container">
        <h1 class="text-center">
            <%= @so_job.title %>
        </h1>
        <h3 class="text-center">
            <%= @so_job.categories %>
        </h3>

        <hr>

        <div class="col-md-12">
            <p>
                <%= link_to 'View on Stack Overflow', @so_job.link %>
            </p>
        </div>

        <div class="col-md-12 body-info">
            <h2 class="text-center">About this job</h2>
            <p><%= @so_job.description.html_safe %></p>
        </div>
    </div>
</div>